export const LOGIN_SUCCESS = "LOGIN_SUCCESS"
export const LOGIN_FAIL = "LOGIN_FAIL"
export const LOGIN_REQUEST = "LOGIN_REQUEST"
export const LOG_OUT = "LOG_OUT"
export const LOAD_PROFILE = "LOAD_PROFILE"


export const HOME_VIDOES_SUCCESS = "HOME_VIDOES_SUCCESS"
export const HOME_VIDOES_FAIL = "HOME_VIDOES_FAIL"
export const HOME_VIDOES_REQUEST = "HOME_VIDOES_REQUEST"