export const LOGIN_REQUEST = "LOGIN_REQUEST"
export const LOGIN_SUCCESS = "LOGIN_SUCCESS"
export const LOGIN_FAIL = "LOGIN_FAIL"
export const LOG_OUT = "LOG_OUT"
export const LOAD_PROFILE = "LOAD_PROFILE"


export const HOME_VIDOES_SUCCESS = "HOME_VIDOES_SUCCESS"
export const HOME_VIDOES_FAIL = "HOME_VIDOES_FAIL"
export const HOME_VIDOES_REQUEST = "HOME_VIDOES_REQUEST"

export const SELECTED_VIDEO_REQUEST = "SELECTED_VIDEO_REQUEST"
export const SELECTED_VIDEO_SUCCESS = "SELECTED_VIDEO_SUCCESS"
export const SELECTED_VIDEO_FAIL = "SELECTED_VIDEO_FAIL"

export const CHANNEL_DETAILS_REQUEST = "CHANNEL_DETAILS_REQUEST"
export const CHANNEL_DETAILS_SUCCESS = "CHANNEL_DETAILS_SUCCESS"
export const CHANNEL_DETAILS_FAIL = "CHANNEL_DETAILS_FAIL"

export const SET_SUBSCRIPTION_STATUS = "SET_SUBSCRIPTION_STATUS"